apiVersion: skaffold/v2beta26
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: spanner-emulator
    docker:
      dockerfile: "spanner.Dockerfile"
      cliFlags: ["--platform", "linux/amd64"]
  local:
    useDockerCLI: true
    useBuildkit: true
