apiVersion: apps/v1
kind: Deployment
metadata:
  name: spanner
  namespace: {{ .Values.targetNamespace }}
  labels:
    app: spanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spanner
  template:
    metadata:
      labels:
        app: spanner
    spec:
      containers:
      - name: spanner
        image: {{ .Values.spannerImageName }}
        imagePullPolicy: IfNotPresent
        args: ["create"]
        ports:
        - name: spanner-port-g
          containerPort: 9010
          protocol: TCP
        - name: spanner-port-r
          containerPort: 9020
          protocol: TCP
        env:
        - name: SPANNER_DB
          value: {{ .Values.spannerDB }}
        - name: SPANNER_DATA
          value: {{ .Values.spannerData }}
        - name: SPANNER_EMULATOR_HOST
          value: "localhost:9010"
---
apiVersion: v1
kind: Service
metadata:
  name: spanner-service
  namespace: {{ .Values.targetNamespace }}
  labels:
    app: spanner
spec:
  ports:
  - name: spanner-port-g
    port: 9010
    targetPort: 9010
    protocol: TCP
  - name: spanner-port-r
    port: 9020
    targetPort: 9020
    protocol: TCP
  selector:
    app: spanner
